//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2APIful.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public System.DateTime Nascimento { get; set; }
        public string Posicao { get; set; }
        public Nullable<int> QTDEFaltas { get; set; }
        public Nullable<int> QTDECartoesAmarelo { get; set; }
        public Nullable<int> QTDECartoesVermelho { get; set; }
        public Nullable<int> QTDEGols { get; set; }
        public string Informacoes { get; set; }
        public Nullable<int> NumeroCamisa { get; set; }
        public Nullable<int> SelecaoID { get; set; }
    
        public virtual Imagens Imagens { get; set; }
        public virtual Selecao Selecao { get; set; }
    }
}
