//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2APIful.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogo
    {
        public int Id { get; set; }
        public Nullable<int> SelecaoCasa { get; set; }
        public Nullable<int> SelecaoVisitante { get; set; }
        public int PlacarCasa { get; set; }
        public int PlacarVisitante { get; set; }
        public int PenaltisCasa { get; set; }
        public int PenaltisVisitante { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Estadio { get; set; }
    
        public virtual Estadio Estadio1 { get; set; }
        public virtual Selecao Selecao { get; set; }
        public virtual Selecao Selecao1 { get; set; }
    }
}
